name: deploy
on: workflow_dispatch
jobs:
  deploy-project:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: cd ./project
      - run: npm install
      - run: npm run build
      - run: npm run deploy
